export const AUTH_REGISTRATION_LOADING = 'AUTH_REGISTRATION_LOADING';
export const AUTH_REGISTRATION_ERROR = 'AUTH_REGISTRATION_ERROR';
export const AUTH_REGISTRATION_RESET = 'AUTH_REGISTRATION_RESET';
