export const USER_CURRENT_COMPAGNY_LOADING = 'USER_CURRENT_COMPAGNY_LOADING';
export const USER_CURRENT_COMPAGNY_ERROR = 'USER_CURRENT_COMPAGNY_ERROR';
export const USER_CURRENT_COMPAGNY_RESET = 'USER_CURRENT_COMPAGNY_RESET';
export const USER_CURRENT_COMPAGNY_SUCCESS = 'USER_CURRENT_COMPAGNY_SUCCESS';
