export const USER_DELETE_LOADING = 'USER_DELETE_LOADING';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
