export const USER_EDIT_LOADING = 'USER_EDIT_LOADING';
export const USER_EDIT_ERROR = 'USER_EDIT_ERROR';
export const USER_EDIT_RESET = 'USER_EDIT_RESET';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
