export const USER_PASSWORD_LOADING = 'USER_PASSWORD_LOADING';
export const USER_PASSWORD_ERROR = 'USER_PASSWORD_ERROR';
export const USER_PASSWORD_RESET = 'USER_PASSWORD_RESET';
export const USER_PASSWORD_SUCCESS = 'USER_PASSWORD_SUCCESS';
