version: '3'

volumes:
  database: {}

services:
  database:
    build: ./docker/postgres
    ports:
      - '5432:5432'
    volumes:
      - '.:/var/www:cached'
      - 'database:/var/lib/postgresql/data'

  node:
    build: ./docker/node
    depends_on:
      - database
      - mercure
    volumes:
      - '.:/var/www:cached'
    ports:
      - 3000:3000

  mercure:
    image: dunglas/mercure
    environment:
      - CORS_ALLOWED_ORIGINS=*
      - JWT_KEY=abc
      - DEBUG=1
      - DEMO=1
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337
    ports:
      - 1337:80
