export const INPUT_LIST_LOADING = 'INPUT_LIST_LOADING';
export const INPUT_LIST_SUCCESS = 'INPUT_LIST_SUCCESS';
export const INPUT_LIST_ERROR = 'INPUT_LIST_ERROR';
export const INPUT_LIST_RESET = 'INPUT_LIST_RESET';
