export const QUOTES_DELETE_LOADING = 'QUOTES_DELETE_LOADING';
export const QUOTES_DELETE_ERROR = 'QUOTES_DELETE_ERROR';
export const QUOTES_DELETE_RESET = 'QUOTES_DELETE_RESET';
export const QUOTES_DELETE_SUCCESS = 'QUOTES_DELETE_SUCCESS';
