export const QUOTES_LIST_LOADING = 'QUOTES_LIST_LOADING';
export const QUOTES_LIST_SUCCESS = 'QUOTES_LIST_SUCCESS';
export const QUOTES_LIST_ERROR = 'QUOTES_LIST_ERROR';
export const QUOTES_LIST_RESET = 'QUOTES_LIST_RESET';
