export const QUOTES_SHOW_LOADING = 'QUOTES_SHOW_LOADING';
export const QUOTES_SHOW_ERROR = 'QUOTES_SHOW_ERROR';
export const QUOTES_SHOW_RESET = 'QUOTES_SHOW_RESET';
export const QUOTES_SHOW_SUCCESS = 'QUOTES_SHOW_SUCCESS';
