export const COMPAGNY_JOIN_LOADING = 'COMPAGNY_JOIN_LOADING';
export const COMPAGNY_JOIN_ERROR = 'COMPAGNY_JOIN_ERROR';
export const COMPAGNY_JOIN_RESET = 'COMPAGNY_JOIN_RESET';
export const COMPAGNY_JOIN_SUCCESS = 'COMPAGNY_JOIN_SUCCESS';
