export const COMPAGNY_LEAVE_LOADING = 'COMPAGNY_LEAVE_LOADING';
export const COMPAGNY_LEAVE_ERROR = 'COMPAGNY_LEAVE_ERROR';
export const COMPAGNY_LEAVE_RESET = 'COMPAGNY_LEAVE_RESET';
export const COMPAGNY_LEAVE_SUCCESS = 'COMPAGNY_LEAVE_SUCCESS';
