export const COMPAGNY_LIST_LOADING = 'COMPAGNY_LIST_LOADING';
export const COMPAGNY_LIST_SUCCESS = 'COMPAGNY_LIST_SUCCESS';
export const COMPAGNY_LIST_ERROR = 'COMPAGNY_LIST_ERROR';
export const COMPAGNY_LIST_RESET = 'COMPAGNY_LIST_RESET';
