version: '3'

volumes:
  database: {}

services:
  database:
    image: postgres:12.4
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: topflop
      PGUSER: docker
      PGPASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './:/var/www:cached'
    ports:
      - 8080:3000
    command: npm run start:dev
